### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by laurivosandi** [mate-desktop-legacy-archive/mate-file-manager-image-converter#4]
Why the heck you're using imagemagick to rotate images? Jpegtran permits lossless rotation of JPEG images and I think it's also significantly faster.

**Comment by infirit** [comment]
Feel free to send in a patch/pull request on https://github.com/mate-desktop/caja-extensions/pulls

**Comment by benpicco** [comment]
Are you sure imagemagick isn't performing lossless rotation as well?
Otherwise this would be pretty [easy to fix](https://github.com/mate-desktop/caja-extensions/blob/master/image-converter/caja-image-rotator.c#L266).

**Comment by infirit** [comment]
It does and doesn't. The rotate action internally is lossless but the writing to another jpeg file is not.

**Comment by infirit** [comment]
Also, do note the extension does not **only** deal with jpeg images. It supports any (mime type image/*) file imagemagic handles so you will have to code in a special exemption of jpeg.
